# Generated by Django 4.0.1 on 2022-01-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0002_lineup_manager_matchday_alter_match_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_injured',
        ),
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(default=None, null=True),
        ),
    ]
