# Generated by Django 4.0.1 on 2022-01-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0003_rename_owner_manager_user_remove_player_is_injured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
