# Generated by Django 4.0.1 on 2022-01-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0004_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='captain_factor',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='lineup',
            name='captain',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
