# Generated by Django 4.0.1 on 2022-01-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0005_league_captain_factor_lineup_captain_player_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
