# Generated by Django 4.0.1 on 2022-01-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0006_remove_player_date_of_birth_remove_player_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='aoe2net',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='icon',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='liquipedia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='icon',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='liquipedia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
