# Generated by Django 4.0.1 on 2022-01-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0009_alter_player_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='offered',
            field=models.BooleanField(default=False),
        ),
    ]
