# Generated by Django 4.0.1 on 2022-01-16 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0010_player_offered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='offered',
        ),
    ]
