# Generated by Django 4.0.1 on 2022-01-16 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0011_remove_player_offered'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=None, null=True)),
                ('end_date', models.DateTimeField(default=None, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_league', to='boa.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tr_player', to='boa.player')),
            ],
        ),
    ]
