# Generated by Django 4.0.1 on 2022-01-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0012_transfermarket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='boa.manager'),
        ),
    ]
