# Generated by Django 4.0.1 on 2022-01-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0013_alter_offer_reciever'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfermarket',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_manager', to='boa.manager'),
        ),
    ]
