# Generated by Django 4.0.1 on 2022-01-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0014_transfermarket_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfermarket',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
