# Generated by Django 4.0.1 on 2022-01-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0015_transfermarket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='budget',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(default='Team', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='def_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transfermarket',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
