# Generated by Django 4.0.1 on 2022-01-27 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0016_alter_manager_budget_alter_manager_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='captain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='flank1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flank1', to='boa.player'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='flank2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flank2', to='boa.player'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='pocket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pocket', to='boa.player'),
        ),
        migrations.AlterField(
            model_name='transfermarket',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transfermarket',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tr_manager', to='boa.manager'),
        ),
    ]
