# Generated by Django 4.0.1 on 2022-01-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0017_alter_lineup_captain_alter_lineup_flank1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lineup_manager', to='boa.manager'),
            preserve_default=False,
        ),
    ]
