# Generated by Django 4.0.1 on 2022-01-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0018_lineup_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='flank1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flank1', to='boa.player'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='flank2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flank2', to='boa.player'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='pocket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pocket', to='boa.player'),
        ),
    ]
