# Generated by Django 4.0.1 on 2022-01-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0019_alter_lineup_flank1_alter_lineup_flank2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='match_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_day', to='boa.player'),
        ),
    ]
