# Generated by Django 4.0.1 on 2022-02-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0020_alter_lineup_match_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchday',
            name='name',
        ),
        migrations.AlterField(
            model_name='match',
            name='liquipedia',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
