# Generated by Django 4.0.1 on 2022-02-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0021_remove_matchday_name_alter_match_liquipedia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='liquipedia',
        ),
    ]
