# Generated by Django 4.0.1 on 2022-02-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0022_remove_match_liquipedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='long_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
