# Generated by Django 4.0.1 on 2022-02-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0023_team_long_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='transfers_per_day',
            field=models.IntegerField(default=5),
        ),
    ]
