# Generated by Django 4.0.1 on 2022-02-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0024_league_transfers_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='points_for_position',
            field=models.FloatField(default=0.2),
        ),
    ]
