# Generated by Django 4.0.1 on 2022-05-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boa', '0036_merge_20220525_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='l1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l1', to='boa.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='l2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l2', to='boa.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='l3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l3', to='boa.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='mvp1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp1', to='boa.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='mvp2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp2', to='boa.player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='league',
            name='transfers_per_day',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='matchday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='l_match_day', to='boa.matchday'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='budget',
            field=models.IntegerField(default=2500),
        ),
        migrations.AlterField(
            model_name='manager',
            name='icon',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matchday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='matchday',
            name='tournament_round',
            field=models.CharField(choices=[('G1', 'Group stage round 1'), ('G2', 'Group stage round 2'), ('G3', 'Group stage round 3'), ('16', 'Round of 16'), ('8', 'Quarter-Finals'), ('4', 'Semi-Finals'), ('2', 'Finals')], max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='result',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transfermarket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
