PREFIXES = ('The Unbelievable', 
           'Los',
           'International',
           'Drushing',
           'Iron',
           'Unloomed',
           'Fully Upgraded',
           'Legends of',
           'Professional',
           'United',
           'Official',
           'Unranked',
           'Unupgraded',           
           'Age of',
)


MIDFIXES = ('Imperial',
            'Feudal',
            'Dark Age',
            'Daut',
            'Boar-Stealing',
            'Idle',
            'Mangudai',
            'Feitoria',
            'Douching',
            'Forest Nothing',
            'Idle TC',
            'VULULU',
            'Hussar-Spamming',
            'Voobly',
            'Low Elo',
            'Flaming',
            'Twitch Chat',
            'Booming',
            'Arena',
            'Farimba',
            'Ballistic',
            'Redemption',
            'HD-Edition',
            'All-In',
            'Empires',
            'Walling',
            'Hoang',
            'Siege',
            'Alt-F4',
)


SUFFIXES = ('105ers',
            'Crusaders',
            'Knights',
            'Legion',
            'Snakes',
            'Wheelbarrows',
            'Dautis',
            'Nomads',
            'Villagers',
            'United',
            'Conquistadors',
            'Missionaries',
            'Petards',
            'Rushers',
            'Lamers',
            'Hippos',
            'Meta Slaves',
            'Experts',
            'Enjoyers',
            'of Empires',
            'Generation',
            'Guild',
            'Clan',
            'Squadron',
            'Raiders',
            'Fanboys',
            'Clickers',
            'Boomers',
            'Strategy'
)
