N_PLAYERS = 4
MAX_PLAYERS_PER_TEAM = 6
POINTS_PER_GAME_WIN = 1
POINTS_PER_GAME_LOSS = -.5
POINT_FOR_MVP = .3
CAPTAIN_FACTOR = 2.
POINTS_FOR_POSITION = .2
POINTS_FOR_EMPTY = -1
POINTS_FOR_VOTE1 = 5
POINTS_FOR_VOTE2 = 3
POINTS_FOR_VOTE3 = 1


# number of leagues a user can administrate
MAX_LEAGUES_PER_ADMIN = 10
TRANSFERS_PER_DAY = 8
START_BUDGET = 2500
