MAX_PLAYERS_PER_TEAM = 4
POINTS_PER_MATCH_WIN = 1
POINTS_PER_MATCH_LOSS = -.5
POINT_FOR_MVP = .3
CAPTAIN_FACTOR = 2.
POINTS_FOR_POSITION = .2
POINTS_FOR_EMPTY = -1

# number of leagues a user can administrate
MAX_LEAGUES_PER_ADMIN = 10
TRANSFERS_PER_DAY = 6
START_BUDGET = 2500
